### ISSUE TITLE
Error in atomsLoad while loading sciFLT

### ISSUE THREAD

**Issue by fernandodemorais-jf** [holgern/sciflt#2]
Hello!

When I load sciFLT-0.5 on Scilab 6.0.2, I get an exec error on line #33 of sciFLT that states that the libf2c.so.2 is not present, but I installed the f2c package.
I am running Scilab 6.0.2 on Arch Linux.
After reinstalling f2c package, I looked for libf2c.so.2, but it doesn't really exist. The same is true when compiling f2c manually form source files.

Is the sciFLT trying to load a shared library that does not exist?

**Comment by tanchinluh** [comment]
Just some add-on, if you have successfully install the f2c, you should be able to see the 
lib files under /usr/lib . you could inspect by :

ls libf2c*

if you see any of them but not libf2c.so.2, try to create a symbolic link by:

sudo ln -s libf2c.so  libf2c.so.2

and launch scilab again.

hope this helps.

CL

**Comment by fernandodemorais-jf** [comment]
Thank you, Tan Chin Luh!

It worked like a charm, after creating the symbolic link.
